version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8501:8501
  chatapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8502:8502

      